server:
  port: 8761
spring:
  security:
    user:
      name: yangl
      password: yangl
  application:
    name: bms-eureka-server
eureka:
  client:
    #是否从其他节点同步数据
    fetch-registry: false
    #是否将自己注册到eureka server
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://yangl:yangl@localhost:${server.port}/eureka/
  instance:
    hostname: localhost