server:
  port: 8761
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

spring:
  security:
    user:
      name: yangl
      password: yangl
  application:
    name: bms-eureka-server
eureka:
  client:
    #是否从其他节点同步数据
    fetch-registry: false
    #是否将自己注册到eureka server
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://yangl:yangl@${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost