server:
  port: 8001

spring:
  application:
    name: bms-auth-server
  profiles:
    active: dev
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://yangl:yangl@localhost:8761/eureka

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.github.plei.entity