spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.3.128:3306/bms-boot?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    hikari:
      maximum-pool-size: 10 #连接池最大连接数
      minimum-idle: 0 #允许的最小空闲数
      idle-timeout: 180000 #空闲超时是 180000 毫秒，当数据库连接的空闲时间大于180000毫秒时，这些空闲超时的连接会被关闭，直到超时的空闲连接数达到 minimum-idle的值
      connection-test-query: select 1 # 测试连接是否可用的query 语句 在oracle是 select 1 from dual

  #redis配置
  redis:
    host: 192.168.3.128
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）